services:
  cippapi:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/site/wwwroot
    develop:
      watch:
        - action: sync
          path: .
          target: /home/site/wwwroot
          ignore:
            - .git/
            - .vscode/
            - .venv/
            - __pycache__/
            - .env
            - .env.*
    environment:
      - FUNCTIONS_WORKER_RUNTIME=${FUNCTIONS_WORKER_RUNTIME}
      - FUNCTIONS_WORKER_RUNTIME_VERSION=${FUNCTIONS_WORKER_RUNTIME_VERSION}
      - AzureWebJobsStorage=${AzureWebJobsStorage}
      - DEV_SKIP_BPA_TIMER=${DEV_SKIP_BPA_TIMER}
      - DEV_SKIP_DOMAIN_TIMER=${DEV_SKIP_DOMAIN_TIMER}
      - FUNCTIONS_EXTENSION_VERSION=${FUNCTIONS_EXTENSION_VERSION}
      - AzureWebJobs.BestPracticeAnalyser_OrchestrationStarterTimer.Disabled=true
      - AzureWebJobs.Domain_OrchestrationStarterTimer.Disabled=true
      - WEBSITE_HOSTNAME=cippapi
      - NonLocalHostAzurite=${NonLocalHostAzurite}
      - ExternalDurablePowerShellSDK=true
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
      - AzureFunctionsJobHost__Logging__LogLevel__Default=Error
      - AzureFunctionsJobHost__Logging__LogLevel__Host.Function=Information
      - AzureFunctionsJobHost__Logging__LogLevel__Function=Information
      - AzureFunctionsJobHost__Logging__LogLevel__Microsoft.Azure.WebJobs.Script.WebHost.Middleware=Information
      - AzureFunctionsJobHost__Logging__LogLevel__Host=Error
      - AzureFunctionsJobHost__Logging__LogLevel__Azure=Error
      - AzureFunctionsJobHost__Logging__LogLevel__Azure.Core=Error
      - AzureFunctionsJobHost__Logging__LogLevel__Azure.Storage=Error
      - AzureFunctionsJobHost__Logging__LogLevel__System=Error
      - AzureFunctionsJobHost__Logging__LogLevel__Microsoft=Error
      - AzureFunctionsJobHost__Logging__LogLevel__DurableTask=Error
      - WEBSITES_INCLUDE_CLOUD_CERTS=true
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - func-network
    deploy:
      replicas: 3

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "7071:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - cippapi
    networks:
      - func-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://cippapi:7071"]
      interval: 30s
      retries: 5

networks:
  func-network:
    driver: bridge
